version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    target-branch: "main"
