version: "3.6"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  
  backend:
    build: ./backend
    ports:
      - "8080:8080"
  
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"