version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    container_name: web

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/app/backend
    depends_on:
      - database
    container_name: api

  nginx:
    image: nginx
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    container_name: nginx

  database:
    image: postgres
    env_file:
      - ./backend/database.env
    ports:
      - "5432:5432"
    container_name: postgres
