version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: website

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./backend:/go/app/backend
    container_name: api

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  
  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./backend/database.env
    ports:
      - "5432:5432"
    container_name: postgres
