# See https://toml.io/ for configuration file syntax

[database]
# Database connection configuration
POSTGRES_USER = "hunter_is_a_GOAT"
POSTGRES_DB = "daBase"                                     # Name of the database
POSTGRES_PASSWORD = "bawlz2daWALLZ"
POSTGRES_INITDB_ARGS = "--data-checksums"
POSTGRES_INITDB_WALDIR = "-z"
POSTGRES_HOST_AUTH_METHOD = "insert text"
PGDATA = "None, there is no pg data. Stop looking for it."

[system]
save_dir = "./pfs_storage/" # Directory for saving files, will be created if it doesn't exist.

[defaults]
# Max storage capacity.
#
# This is different than the system storage, this defines
# the maximum intake for the data as a total.
max_storage = inf

# Expiration time for data before deletion in Unix Timestamp format.
# Seen as the current time + expiration time.
#
# Don't expire = 0
# Expire after 1 day = 86400
# Expire after 1 week = 604800
# Expire after 1 month = 2592000
expiry = 259200 # 3 days
