root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "tmp/main"
# bin = "tmp\\main"
cmd = "go build -o ./tmp/main ."
# cmd = "go run main.go"
delay = 1000
exclude_dir = ["tmp"]
include_ext = ["go"]
log = "build-errors.log"
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

# [screen]
# clear_on_rebuild = false
