name: CI

on:
  push:
  pull_request:

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Format and Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --fix
          working-directory: backend

      - name: Generate Diff
        run: git diff > Go.diff

      - run: cat Go.diff

      - name: Upload Diff as Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: Go.diff
          name: Go
  Shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: shellcheck ./start-pfs.sh -S style
        # shellcheck is already installed on GitHub Actions CI machines

      - name: Format and Generate Diff
        run: shellcheck ./start-pfs.sh -f diff > Shell.diff

      - run: cat Shell.diff

      - name: Upload Diff as Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: Shell.diff
          name: Shell
  Node:
    name: Svelte/TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Lint
        working-directory: frontend
        run: npm run check

      - name: Format
        working-directory: frontend
        run: npm run format

      - name: Generate Diff
        run: git diff > SvelteTS.diff

      - run: cat SvelteTS.diff

      - name: Upload Diff as Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: SvelteTS.diff
          name: SvelteTS
  Push:
    runs-on: ubuntu-latest
    name: Push Changes
    needs: [Go, Shell, Node]
    if: github.event_name != 'pull_request'
    env:
      CHANGED: false
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve Diff Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./artifacts/

      - name: Apply Diffs
        run: |
          git apply --allow-empty ./artifacts/Go/Go.diff 
          git apply --allow-empty ./artifacts/SvelteTS/SvelteTS.diff
          git apply --allow-empty ./artifacts/Shell/Shell.diff

      - name: Check if a change has been made
        continue-on-error: true
        run: |
          git diff --quiet --exit-code HEAD
          if [ "$?" = "1" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Setup Git CI Commiter Information
        if: env.CHANGED == true
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push Changes
        if: env.CHANGED == true
        run: |
          git add .
          git commit -m "Format Code"
          git push origin ${{ github.ref }}
