name: "Docker Builds"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file: ["./dev-docker-compose.yml", "./docker-compose.yml"]

    steps:
      - uses: actions/checkout@v2
      - run: docker compose -f ${{ matrix.file }} up
