name: "Docker Image"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: ["dev", "prod"]

    steps:
      - uses: actions/checkout@v3
      - run: ./start-pfs.sh -e ${{ matrix.env }} -v
