name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangcilint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: GoLangCI
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./cli

      - name: Generate Diff
        run: git diff > Go.diff

      - name: Upload Diff as Artifact
        uses: actions/upload-artifact@v3
        with:
          path: Go.diff

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Build Go
        working-directory: backend
        run: go build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
