name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: GoLang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./backend
