name: Shell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt install shellcheck

      - name: Lint
        continue-on-error: true
        run: shellcheck ./start-pfs.sh
  Format:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Install shfmt
        run: gh release download -R mvdan/sh --pattern shfmt_v3.5.1_linux_amd64

      - name: Format
        run: shfmt -d -bn -i 4 ./start-pfs.sh

      - name: Generate Diff
        run: git diff > Shell.diff

      - name: Upload Diff as Artifact
        uses: actions/upload-artifact@v3
        with:
          path: Shell.diff
